# This is a basic workflow to help you get started with Actions

name: py-eodms-dds Version Check

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: 'development'

      # List files
      - name: List files
        run: ls
      
      # Install package from setup.py
      - name: Install package from setup.py
        run: |
          sudo python setup.py install
          sudo pip install py-eodms-rapi -U

      # Runs a single command using the runners shell
      - name: Run py-eodms-dds Version Check
        # continue-on-error: true
        run: |
          SETUP_VERSION="$(python setup.py --version)"
          CFG_VERSION="$(python -c 'from setuptools.config.setupcfg import read_configuration as c; print(c("setup.cfg")["metadata"]["version"])')"
          PK_VERSION="$(python -c 'from eodms_dds import __version__; print(__version__)'"

          if [[ "$SETUP_VERSION" != "$CFG_VERSION" ]] && [[ "$SETUP_VERSION" != "$PK_VERSION" ]] && [[ "$CFG_VERSION" != "$PK_VERSION" ]]; then
            echo "All three variables are not equal"
          else
            echo "At least two variables are equal"
          fi
