# This is a basic workflow to help you get started with Actions

name: py-eodms-dds Tests

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: 'main'

      # List files
      - name: List files
        run: ls
      
      # Install package from setup.py
      - name: Install package from setup.py
        run: |
          sudo python setup.py install
          sudo pip install py-eodms-rapi -U

      # Runs a single command using the runners shell
      - name: Run py-eodms-dds Test 1 - RAPI and DDS Search and Order
        # continue-on-error: true
        env:
          EODMS_USER: ${{ secrets.EODMS_USER }}
          EODMS_PASSWORD: ${{ secrets.EODMS_PWD }}
        run: |
          cd test
          python rapi_dds_test.py -u $EODMS_USER -p $EODMS_PASSWORD -c RCMImageProducts
